### ISSUE TITLE
Windows compliance broke

### ISSUE THREAD

**Issue by bedroesb** [ResearchObject/ro-crate-py#16]
```
Traceback (most recent call last):
  File ".\ro_crate_example_readme.py", line 11, in <module>
    wf_crate.write_zip(out_path)
  File "C:\Users\bertd\AppData\Local\Programs\Python\Python38\lib\site-packages\rocrate\rocrate.py", line 367, in write_zip
    writable_entity.write_zip(zf)
  File "C:\Users\bertd\AppData\Local\Programs\Python\Python38\lib\site-packages\rocrate\model\file.py", line 127, in write_zip
    zip_out.write(self.source, self.id)
  File "C:\Users\bertd\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1739, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "C:\Users\bertd\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 521, in from_file
    st = os.stat(filename)
```

**Comment by stain** [comment]
Unable to replicate, #18 indicates tests pass in Windows. Check content of your `ro_crate_example_readme.py` if there is an edge case we have not tested yet, or if this only happens on second run of `ro_crate_example_readme.py` (e.g. `filename` exists already before writing out to it).

**Comment by bedroesb** [comment]
I will try to replicate it offline this evening. If it fails with the same test example, I will show put the example here to have a look

**Comment by bedroesb** [comment]
@stain The windows problem is fixed
